# .github/workflows/update-news.yml
name: Generate Daily News

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # This is the schedule trigger
  schedule:
    # Runs at 08:00 my time (01:00 UTC) every day.
    # You can use https://crontab.guru to customize the time.
    - cron: '0 1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a newer version

      - name: Set up Python
        uses: actions/setup-python@v5 # Use a newer version
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the news generation script
        run: python generate_news.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Use a newer version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          # This will commit the generated index.html to a special 'gh-pages' branch
